// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqggnbvvfhsakjlaklx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcWdnbmJ2dmZoc2Framxha2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjAwMTEsImV4cCI6MjA3NDA5NjAxMX0.Z_hFBtGfIZP4omIAfl7UgnAOYdumUcS4oJnHl-L221Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});